---
apiVersion: v1
kind: Pod
metadata:
  name: 192.168.16.19
  labels:
    app: nginx1
spec:
  nodeSelector:
    kubernetes.io/hostname: node-01
  containers:
    - name: nginx1
      securityContext:
        privileged: true
      image: nginx:alpine
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
    app: nginx2
spec:
  nodeSelector:
    kubernetes.io/hostname: worker2
  containers:
    - name: nginx2
      securityContext:
        privileged: true
      image: nginx:alpine
      ports:
        - containerPort: 80
---
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-test
  labels:
    app: nginx
spec:
  nodeSelector:
    kubernetes.io/hostname: node2
  containers:
    - name: nginx-test
      securityContext:
        privileged: true
      image: nginx:alpine
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-node1
  labels:
    app: nginx
spec:
  nodeSelector:
    kubernetes.io/hostname: node1
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    - effect: NoSchedule
      operator: Exists
    - effect: NoExecute
      operator: Exists
  containers:
    - name: nginx-master
      securityContext:
        privileged: true
      image: nginx:alpine
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-node1-nodeport
  labels:
    app: nginx111
spec:
  nodeSelector:
    kubernetes.io/hostname: node1
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    - effect: NoSchedule
      operator: Exists
    - effect: NoExecute
      operator: Exists
  hostNetwork: true
  containers:
    - name: nginx-master
      securityContext:
        privileged: true
      image: nginx:alpine
      ports:
        - containerPort: 80
          hostPort: 80