---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-worker1
  labels:
    app: nginx
spec:
  nodeSelector:
    kubernetes.io/hostname: worker1
  containers:
    - name: nginx-worker1-1
      image: nginx:alpine
      ports:
        - containerPort: 80
    - name: nginx-worker1-2
      image: busybox:1.31.1
      command: ["sleep"]
      args: ["10000"]
