---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-worker1
  labels:
    app: nginx
spec:
  nodeSelector:
    kubernetes.io/hostname: worker1
  containers:
    - name: nginx-worker1
      securityContext:
        privileged: true
      image: nginx:alpine
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-worker2
  labels:
    app: nginx
spec:
  nodeSelector:
    kubernetes.io/hostname: worker2
  containers:
    - name: nginx-worker2
      securityContext:
        privileged: true
      image: nginx:alpine
      ports:
        - containerPort: 80
---
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-test
  labels:
    app: nginx
spec:
  nodeSelector:
    kubernetes.io/hostname: worker2
  containers:
    - name: nginx-test
      securityContext:
        privileged: true
      image: nginx:alpine
      ports:
        - containerPort: 80