name: build

on:
  push:
    tags:
      - "**"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

      - if: ${{ github.ref == 'refs/heads/main' }}
        run: echo ::set-output name=version::latest

      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v2

      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_PUSH_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PUSH_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          file: build/images/release/Dockerfile
          tags: yuanran/dev:${{ steps.get_version.outputs.version }}
          platforms: linux/amd64,linux/arm64
          push: true
